config/routes.rb
ClassMngmt::Application.routes.draw do
  devise_for :students
  resources :assignments

  resources :students

  root to: 'assignments#index'

  namespace :api do
    resources :students
  end

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  scope :pending, -> { where(done: [false, nil]) }
  scope :completed, -> { where(done: true) }
end

app/models/course.rb
class Course < ActiveRecord::Base
  #belongs_to :student, class_name: Student, foreign_key: :student_id

  has_many :course_registrations
  has_many :students, through: :course_registrations

end

app/models/course_registration.rb
class CourseRegistration < ActiveRecord::Base
  belongs_to :course 
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :confirmable
  #has_many :courses
  has_many :course_registrations, dependent: :destroy
  has_many :courses, through: :course_registrations

  #validates_presence_of :email
  validates :email, presence: true, 
                    format: { with: /\w+@\w+\.\w+/, 
                    message: I18n.t('email_format_msg') }
  before_create :set_defaults

  scope :renee, -> { where(full_name: 'Renee') }

private
  def set_defaults
    self.title = "Student" if title.blank?
  end
end

app/controllers/api/students_controller.rb
class Api::Students < ApiController
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_student!
  # GET /assignments
  # GET /assignments.json
  def index
    @pending_assignments = Assignment.pending
    @completed_assignments = Assignment.completed
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to root_path, notice: 'Assignment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @assignment }
      else
        format.html { render action: 'new' }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to root_path, notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:title, :details, :due_date, :done)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    I18n.locale = 'en'
    @students = Student.all

    respond_to do |format|
      format.html
      format.xml {render xml: @students.to_xml}
      format.json #{render json: @students.to_json}
    end

  end

  # GET /students/1
  # GET /students/1.json
  def show
    render 'show', layout: 'hello'
  end

  # GET /students/new
  def new
    I18n.locale = 'fr'
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        WelcomeMailer.welcome_student(@student).deliver
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:full_name, :title, :bio, :age, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper

  def display_bio(student)
    truncate(student.bio, length: 12)
  end
end

app/views/assignments/_assignments_list.html.erb
<% assignments.each do |assignment| %>
  <tr>
    <td><%=link_to assignment.title, edit_assignment_path(assignment) %></td>
    <td><%= assignment.details %></td>
    <td><%= assignment.due_date %></td>
    <td><%= assignment.done %></td>
    <td><%= link_to 'Show', assignment %></td>
    <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<h1>My Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Details</th>
      <th>Due date</th>
      <th>Done</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <tr><th>Pending Assignments</th></tr>
    <%= render 'assignments_list', 
        assignments: @pending_assignments %>
      <tr><th>Completed Assignments</th></tr>
  <%= render 'assignments_list', 
      assignments: @completed_assignments %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @assignment.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @assignment.details %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @assignment.due_date %>
</p>

<p>
  <strong>Done:</strong>
  <%= @assignment.done %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClassMngmt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/header' %>

<%= yield %>

</body>
</html>

app/views/layouts/hello.html.erb
hi
<%= yield %>

app/views/shared/_header.html.erb
<% if current_student %>
  You are logged in as: <%= current_student.email %> from: <%= current_student.current_sign_in_ip %> 
  <%= link_to 'Logout', destroy_student_session_path, method: :delete %>
<% else %>
<%= link_to 'Login', new_student_session_path %>
<% end %>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>My Students</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Title</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.full_name, student %></td>
        <td><%= student.title %></td>
       <td><%= display_bio student %></td>
      <!--   <td><%= student.age %></td> -->
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @student.full_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @student.title %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @student.bio %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>